[25-Mar-2019 21:29:25 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 21:31:11 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 21:43:12 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 21:47:11 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:18:11 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:46:36 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:46:36 UTC] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unexpected "raw" tag (expecting closing tag for the "block" tag defined near line 4). in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig:8
Stack trace:
#0 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/TokenParser/Block.php(38): Twig_Parser->subparse(Array, true)
#1 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(168): Twig_TokenParser_Block->parse(Object(Twig_Token))
#2 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(81): Twig_Parser->subparse(NULL, false)
#3 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(533): Twig_Parser->parse(Object(Twig_TokenStream))
#4 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(565): Twig_Environment->parse(Object(Twig_TokenStream))
#5 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(368): Twig_Environment->compileSource(Object(Twig_Source))
#6 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig on line 8
[25-Mar-2019 22:53:00 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:53:00 UTC] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unexpected "raw" tag (expecting closing tag for the "block" tag defined near line 4). in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig:8
Stack trace:
#0 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/TokenParser/Block.php(38): Twig_Parser->subparse(Array, true)
#1 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(168): Twig_TokenParser_Block->parse(Object(Twig_Token))
#2 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(81): Twig_Parser->subparse(NULL, false)
#3 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(533): Twig_Parser->parse(Object(Twig_TokenStream))
#4 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(565): Twig_Environment->parse(Object(Twig_TokenStream))
#5 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(368): Twig_Environment->compileSource(Object(Twig_Source))
#6 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig on line 8
[25-Mar-2019 22:54:59 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:54:59 UTC] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unexpected "raw" tag (expecting closing tag for the "block" tag defined near line 4). in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig:8
Stack trace:
#0 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/TokenParser/Block.php(38): Twig_Parser->subparse(Array, true)
#1 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(168): Twig_TokenParser_Block->parse(Object(Twig_Token))
#2 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(81): Twig_Parser->subparse(NULL, false)
#3 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(533): Twig_Parser->parse(Object(Twig_TokenStream))
#4 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(565): Twig_Environment->parse(Object(Twig_TokenStream))
#5 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(368): Twig_Environment->compileSource(Object(Twig_Source))
#6 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig on line 8
[25-Mar-2019 22:55:01 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:55:01 UTC] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unexpected "raw" tag (expecting closing tag for the "block" tag defined near line 4). in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig:8
Stack trace:
#0 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/TokenParser/Block.php(38): Twig_Parser->subparse(Array, true)
#1 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(168): Twig_TokenParser_Block->parse(Object(Twig_Token))
#2 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Parser.php(81): Twig_Parser->subparse(NULL, false)
#3 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(533): Twig_Parser->parse(Object(Twig_TokenStream))
#4 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(565): Twig_Environment->parse(Object(Twig_TokenStream))
#5 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig/Environment.php(368): Twig_Environment->compileSource(Object(Twig_Source))
#6 /Applications/MAMP/htdocs/web-app/vendor/twig/twig/lib/Twig in /Applications/MAMP/htdocs/web-app/App/Views/500.html.twig on line 8
[25-Mar-2019 22:56:45 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:57:00 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 22:58:01 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:20:56 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:21:50 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:29:01 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:29:24 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:29:38 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
[25-Mar-2019 23:42:21 UTC] Uncaught exception: 'ErrorException' with message 'file_get_contents(http://45.63.49.226:8000/api/query): failed to open stream: Connection refused'
Stack trace: #0 [internal function]: Core\Error::errorHandler(2, 'file_get_conten...', '/Applications/M...', 70, Array)
#1 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(70): file_get_contents('http://45.63.49...')
#2 /Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php(50): App\Controllers\Devices->parseDevices()
#3 [internal function]: App\Controllers\Devices->myDevicesAction()
#4 /Applications/MAMP/htdocs/web-app/Core/Controller.php(39): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/web-app/Core/Router.php(108): Core\Controller->__call('myDevices', Array)
#6 /Applications/MAMP/htdocs/web-app/public/index.php(44): Core\Router->dispatch('Devices/my-devi...')
#7 {main}
Thrown in '/Applications/MAMP/htdocs/web-app/App/Controllers/Devices.php' on line 70
